### ISSUE TITLE
General Review

### ISSUE THREAD

**Issue by LinaYahya** [GSG-G11/herfa#67]
1- 
https://github.com/GSG-G11/herfa/blob/d07732d65a0ab7ac2c6902009f5b30adb0fe767b/client/public/index.html#L5
change to 
```html
 <link rel="icon" href="/favicon.ico" /> 
```
2- 
https://github.com/GSG-G11/herfa/blob/d07732d65a0ab7ac2c6902009f5b30adb0fe767b/server/database/models/review.js#L12
Change to 
```js
 type: Sequelize.FLOAT, 
```

**Comment by RandSohail** [comment]
When creating the database be sure to remove createdAt and updated At 
using the following 
```js
 createdAt: false,
  updatedAt: false,
```

**Comment by RandSohail** [comment]
We have two different validation that validates the same thing => id 
use a general one instead.
https://github.com/GSG-G11/herfa/blob/main/server/utils/validation/requestParamsValidation.js
https://github.com/GSG-G11/herfa/blob/main/server/utils/validation/mainServiceIdValidation.js

**Comment by RandSohail** [comment]
In the utils file, we don't use the index file at all 
use it when call anything from utils folder instead of utils/validation/.. something

**Comment by RandSohail** [comment]
I think the Custom error should be in the utils file, not the controller's error?
https://github.com/GSG-G11/herfa/blob/main/server/controllers/errors/custom.js
